### ISSUE TITLE
Como o usuário escolhe a dimensão da matriz ?

### ISSUE THREAD

**Issue by Gabryel-UFG-discente** [Gabryel-Borges/Matriz-Quadrada#1]

**Comment by Gabryel-Borges** [comment]
Como dito na explicação do projeto, essa matriz é do tipo quadrada, isto significa que a quantidade de linhas é igual a de colunas, por isso o usuário só entra com um único valor, pois esse mesmo valor é atribuído tanto a dimensão vertical (linhas), quanto a dimensão horizontal (colunas).
Entenda um pouco melhor de matriz nesse [artigo](https://www.w3schools.com/c/c_arrays_multi.php).
